import tseslint from "@typescript-eslint/eslint-plugin"
import tsParser from "@typescript-eslint/parser"
import sveltePlugin from "eslint-plugin-svelte"
import svelteParser from "svelte-eslint-parser"

export default [
    // typescript файлы
    {
        files: ["**/*.ts"],
        languageOptions: {
            parser: tsParser,
            parserOptions: { project: "./tsconfig.json" },
        },
        plugins: { "@typescript-eslint": tseslint },
        rules: {
            ...tseslint.configs["recommended"].rules,
            "@typescript-eslint/no-explicit-any": "error",
            "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
            "@typescript-eslint/explicit-function-return-type": "warn",
            "@typescript-eslint/no-non-null-assertion": "warn",
            "no-console": ["warn", { allow: ["warn", "error"] }],
            "eqeqeq": ["error", "always"],
            "no-var": "error",
            "prefer-const": "error",
        },
    },

    // svelte файлы
    {
        files: ["**/*.svelte"],
        languageOptions: {
            parser: svelteParser,
            parserOptions: { parser: tsParser },
        },
        plugins: { svelte: sveltePlugin },
        rules: {
            ...sveltePlugin.configs.recommended.rules,
            "no-console": ["warn", { allow: ["warn", "error"] }],
            "prefer-const": "error",
        },
    },
]